# http://www.appveyor.com/docs/appveyor-yml

# init
clone_depth: 20

environment:
  matrix:
  - nodejs_version: 0.12
  - nodejs_version: 3

# install
install:
- ps: Install-Product node $env:nodejs_version
- node --version
- npm --version
- npm install

# build
build: off

# test
test_script:
- npm run verify

# deploy
deploy: off

# notify
notifications:
- provider: Email
  to:
  - o.gata.ken@gmail.com
  on_build_status_changed: true
