# http://www.appveyor.com/docs/appveyor-yml

# init
clone_depth: 20

environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7

# install
install:
- ps: . .\Execute-With-Retry
- ps: Execute-With-Retry { Install-Product node $env:nodejs_version }
- node --version
- npm --version
- windows_retry npm install

# build
build: off

# test
test_script:
- npm run verify

# deploy
deploy: off

# notify
notifications:
- provider: Email
  to:
  - o.gata.ken@gmail.com
  on_build_status_changed: true
